apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: my-cool-prometheus
  namespace: "12345"
      
  labels:
    app-operator.giantswarm.io/version: 1.0.0

spec:
  catalog: giantswarm
  name: prometheus
  namespace: monitoring
  version: 3.2.1
      
  config:
    configMap:
      name: 12345-cluster-values
      namespace: 12345
        
    secret:
      name: 
      namespace: 
      
  kubeConfig: 
    context:
      name: 12345
    inCluster: false
    secret:
      name: 12345-kubeconfig
      namespace: 12345