apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appcatalogs.application.giantswarm.io
spec:
  conversion:
    strategy: None
  group: application.giantswarm.io
  names:
    kind: AppCatalog
    listKind: AppCatalogList
    plural: appcatalogs
    singular: appcatalog
  preserveUnknownFields: true
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            config:
              properties:
                configMap:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    resourceVersion:
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
                secret:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    resourceVersion:
                      type: string
                  required:
                  - name
                  - namespace
                  type: object
              type: object
            description:
              type: string
            logoURL:
              type: string
            storage:
              properties:
                URL:
                  format: uri
                  type: string
                type:
                  type: string
              required:
              - type
              - URL
              type: object
            title:
              type: string
          required:
          - title
          - description
          - storage
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.application.giantswarm.io
spec:
  conversion:
    strategy: None
  group: application.giantswarm.io
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  preserveUnknownFields: true
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true