apiVersion: application.giantswarm.io/v1alpha1
kind: AppCatalog
metadata:
  name: giantswarm
  labels:
    application.giantswarm.io/catalog-type: stable
spec:
  title: Giant Swarm
  description: "Catalog of Apps by Giant Swarm"
  config:
    configMap:
      name: app-catalog-values
      namespace: giantswarm
            
    secret:
      name: app-catalog-secrets
      namespace: giantswarm

  logoURL: "https://s.giantswarm.io/..."
  storage:
    type: helm
    URL: "https://giantswarm.github.io/app-catalog/"