kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-mutating-webhook
webhooks:
  - name: mutating-webhook.openpolicyagent.org
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["application.giantswarm.io"]
        apiVersions: ["v1alpha1"]
        resources: ["apps", "appcatalogs"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQ3lFUkxrbURRTmxUQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt4TWpFMk1URXlOak01V2hnUE1qSTVNekE1TXpBeE1USTJNemxhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUx2bXc0bmlBblVsZWYrUTRndmdCZFg3WC9kRWlseWovRWhPUVVpZ0lIMlJ0Q2ViQncyWHcvT2IKYTYrMTBRUE1sbUxiS0lHQUk4bjNUbFlXU2pTb1BhRFBIMnFXWlU4Q1B1ZGk1NGtjMndrVHlTaGdJUmgyV1ZwZApTVFhpMlZlc2d6ZDAxVkJTcC93N0dmSk5ZaG0vLzlxNkhocU9iZ2c0L1ovcWo5NnFjWFpyS2RQSTQvaFFtT2crCmcvRlVyaE0rNS80bk1yYndhNENXcUVhbmhvMDNGeENuY0FNZEJ6SnVVeTVQVVhYcm12cnRwRGZvaHMxUDZWUXcKbXU1OEpNam5rM1NzdFhQeWFaRTRiVEUzdURFaDBveVoycExJVEZvTkV2YmljcXBMVmlGRFZIR3BpNGVFRTdzZApIUGlVODRsRFRvZzk3Zmk2TVkrdFR6SUt2R2l1cXo4Q0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBClhEY1daazUwUkpHL1Jab2lKd04wRHJXaEtFZGVaS0pkREpLOHd2SXVwSHoza1pBa1RUMmRySC9tbm1Ua1VvOGsKUXk5STBRRUdoVllBajMwMmtFMVljSGthQ2VkMElYb2trS1VzbFZPbzk5amJUM1VTSE5iemJqRjVNQ1cxTjlkUgozNjZqTGdid3gvd0lPNzhUSHp3VUVkRFBjTVpQeXh3MEFmTVg2WDFnNlNoYzNQdERpNXd6dHNiZlZUSWQ3V01JCjNvLzQvNXF3SUVHSlBISTVJY1NPZDJRTGtmUVFpaGxiaE1tZExFcEtUYmgwNU5JV1BiZnpZZ0h4STYva3Z1ZDYKcnQ1RU0yMGMyaytDenlLZG82cEdIY1V5RXMxMi9qV2dTaXZhYjN6ZmtHOHRxT3dFL0hCdnRxYmw0UGxFbUludgp0TlJWcDBtSzJXall6WmRMSHFSc2d3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: opa
        name: opa
