kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: opa-mutating-webhook
webhooks:
  - name: mutating-webhook.openpolicyagent.org
    rules:
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRFNGQk9idUI0aUFqQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3TWpFNU1Ea3lOekkwV2hnUE1qSTVNakV5TURRd09USTNNalJhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU5CTHFFN29qNzRDc0FBL28wTmw1blE1NmhEVElWc2VvdDFrOEtvdlRBWlB1dVNrcXdPb2JWQncKNkFCdWFvTnloSlpjMDRXYXRqM1RCWkJSNHVYd2VIaU9FN1RzTnFDTERmOS8wLzRXZ3IydUNTRU1ZYS9Xak9OUgorWUlISUQycnhlT0k5OEgyTVZuYUtTUVlBUmplSDVXTFg4WWxsR3M0bHFVSXhOYmYzWFBWQWo4WElUV2w2LzFOClFYalpXVUFnZk1nTVNSbHZiRHAxbVFONFIzajdiT0paMnFTYStzODMxU2pUSnVpZ2pFbGRIeWpLajhwNGpWUEQKbXRIUG4rTUZUbFJsNmV2aGoybnQyVXJtNUwvRTBFR25YUDJ0akRIOW5FWmxVY3BmUEJwSFVHaVpEYXpPQVhtcwplMFRQNnZsTmdPYXl6alN4QnpxczU2QnZOVzY1NHVzQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCmp0MGgwcDZ3WTkvZTgyNVNlTXFBRTBUUHdLRkpHamJ0cElKQWZwK1ZNbnArRnNuaTJ5VDdWQS9YeXdoOURmZjYKK1dxVUJlOVZuanFOZ2VsV3VjOGRQdkdrMTBHRWhVWUdwSGppZGpSZXgzQWJPNWdEWkVOMzFlUStwQ09UUXZiYQprY0cyTVlmTWNqWkR3ak9FTmFsN01lYXpBTFZOY3J1MHJRREZpZUYzTUxSMDVLTEZYRVBvN0E0dGNKQUx0VFRDCmdPRU9aYnowaFZ1ZjlmR1Fmem1pWU9xMnJUemNwbXJGVFZMNkhUNEs5bEFmemtJT2ZPbmdGeDFCUlkxa3VnZ2QKWUYwU2YwTS9vTXExQm1pUkt4bzRoMndYRGlqS0RUWnJZZHZBdlVVa1dtbEhhYUMyUS9mK2d6bngwSHZxWmV4TgpQWFMvSkNpU1ZSdzlkc0Y2R1h6OEN3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: opa
        name: opa
